language: node_js
node_js:
- '0.10'
install: npm install; bower install
script: ember build --environment production
branches:
  only:
    - ember-cli
env:
  global:
    secure: LGGMwEEgoh3BpmigoQGG3tuxIrKWPD83DToQktT5yrleiDvE0MbxBZ3ph14mZsq20/B7lgUtZLQ8EASSriRxuRv2HRbV8PD3vCx3J6YpLMe5dKcljElQsT6SO+aWUbpyDaaKZI/tgwGbY6HAoakJzwk0HOVSKXdmjL+SzRfZCpg=
after_success:
  - shopt -s extglob
  - mkdir build_out
  - mv !(build_out) build_out/
  - rm -rf build_out/.git
  - rm -rf build_out/vendor
  - rm -rf build_out/node_modules
  - git clone $AZURE_REPO_URL
  - rm -rf regard-dashboard/*
  - cp -r build_out/* regard-dashboard/
  - cd regard-dashboard
  - git config user.name "Travis-CI"
  - git config user.email "travis@withregard.io"
  - git add -A
  - git add -f dist
  - git commit -m "[$TRAVIS_BUILD_ID] [$TRAVIS_COMMIT_RANGE] [TRAVIS_COMMIT]"
  - git push --force origin master
