language: node_js
node_js:
- '0.10'
install: npm install; bower install
script: ember build --environment production
branches:
  only:
    - ember-cli
env:
  global:
    secure: LGGMwEEgoh3BpmigoQGG3tuxIrKWPD83DToQktT5yrleiDvE0MbxBZ3ph14mZsq20/B7lgUtZLQ8EASSriRxuRv2HRbV8PD3vCx3J6YpLMe5dKcljElQsT6SO+aWUbpyDaaKZI/tgwGbY6HAoakJzwk0HOVSKXdmjL+SzRfZCpg=
after_success:
  - git config user.name "Travis-CI"
  - git config user.email "travis@withregard.io"
  - git clone $AZURE_REPO_URL
  - cp -r dist/* regard-dashboard/
  - cd regard-dashboard
  - git add .
  - git commit -m $TRAVIS_BUILD_ID
  - git push --force origin master
